import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toastError, toastSuccess } from "../components/common/Toast/toastService";
import { getStoredEmployeeId } from "../utils/authStorage";
import { applyResignation, getEmployeeResignation, updateResignation } from "../services/employeeResignationService";
import { dateValue, errorMessage, idOf, resignationRecord, statusOf, unwrap, value } from "./resignationUtils";
import "./Resignation.css";

const empty = { resignationDate: "", lastWorkingDate: "", reason: "", comments: "" };
export default function ApplyResignation() {
  const employeeId = getStoredEmployeeId(); const [record, setRecord] = useState(null); const [form, setForm] = useState(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const navigate = useNavigate();
  const load = async () => { try { const r = await getEmployeeResignation(employeeId); const item = resignationRecord(r.data); setRecord(item); if (item) setForm({ resignationDate: dateValue(value(item,"resignationDate","ResignationDate")), lastWorkingDate: dateValue(value(item,"lastWorkingDate","LastWorkingDate")), reason: value(item,"reason","Reason") || "", comments: value(item,"comments","remarks","Remarks") || "" }); } catch (e) { if (e?.response?.status !== 404) toastError(errorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { if (employeeId) load(); else setLoading(false); }, [employeeId]);
  const editable = !record || ["pending","submitted","applied"].includes(String(statusOf(record)).toLowerCase());
  const submit = async (e) => { e.preventDefault(); if (!form.resignationDate || !form.lastWorkingDate || !form.reason.trim()) return toastError("Resignation date, last working date and reason are required."); if (new Date(form.lastWorkingDate) < new Date(form.resignationDate)) return toastError("Last working date cannot be before resignation date."); const resignationId = record ? idOf(record) : null; if (record && (!Number.isFinite(Number(resignationId)) || Number(resignationId) <= 0)) { console.error("[EmployeeResignation] Invalid resignationId:", resignationId); toastError("Unable to update: the resignation ID is missing or invalid. Refresh the resignation and try again."); return; } setSaving(true); try { const iso = date => `${date}T00:00:00.000Z`; const payload = record ? { resignationId: Number(resignationId), employee_Id: employeeId, resignationDate: iso(form.resignationDate), lastWorkingDate: iso(form.lastWorkingDate), reason: form.reason.trim() } : { resignationDate: iso(form.resignationDate), lastWorkingDate: iso(form.lastWorkingDate), reason: form.reason.trim() }; console.log("[EmployeeResignation] Existing resignation:", record); console.log("[EmployeeResignation] Resignation ID:", resignationId); console.log("[EmployeeResignation] UPDATE payload:", payload); const response = record ? await updateResignation(payload) : await applyResignation(payload); setRecord(resignationRecord(response.data) || payload); toastSuccess(record ? "Resignation updated successfully." : "Resignation submitted successfully."); await load(); } catch (e) { toastError(errorMessage(e)); } finally { setSaving(false); } };
  if (loading) return <div className="resignation-page"><div className="resignation-card"><div className="skeleton-line"/><div className="skeleton-line"/><div className="skeleton-line"/></div></div>;
  return <div className="resignation-page"><div className="resignation-header"><div><h1>Apply Resignation</h1><p>Submit and track your resignation request.</p></div>{record && <span className="resignation-status">{statusOf(record)}</span>}</div><div className="resignation-card">{!employeeId ? <p>Employee profile is unavailable. Please sign in again.</p> : <form onSubmit={submit}><div className="resignation-grid"><label className="resignation-field"><span>Resignation date *</span><input type="date" value={form.resignationDate} disabled={!editable||saving} onChange={e=>setForm({...form,resignationDate:e.target.value})}/></label><label className="resignation-field"><span>Last working date *</span><input type="date" value={form.lastWorkingDate} disabled={!editable||saving} onChange={e=>setForm({...form,lastWorkingDate:e.target.value})}/></label><label className="resignation-field full"><span>Reason *</span><textarea value={form.reason} disabled={!editable||saving} onChange={e=>setForm({...form,reason:e.target.value})}/></label><label className="resignation-field full"><span>Comments</span><textarea value={form.comments} disabled={!editable||saving} onChange={e=>setForm({...form,comments:e.target.value})}/></label></div><div className="resignation-actions">{record && <button type="button" onClick={()=>navigate(`/resignations/${idOf(record)}`)}>View details</button>}{editable && <button type="submit" disabled={saving}>{saving ? "Submitting…" : record ? "Update resignation" : "Submit resignation"}</button>}</div>{record && !editable && <p>This resignation can no longer be edited.</p>}</form>}</div></div>;
}
