import React, { useMemo, useState } from "react";
import { toastError, toastSuccess } from "../components/common/Toast/toastService";
import { createClearance, updateDepartmentClearance } from "../services/employeeClearanceService";
import { clearanceComplete, clearanceError, cv } from "./clearanceUtils";
import { isEmployee } from "../utils/authorization";

const displayValue = (value) => value === null || value === undefined || String(value).trim() === "" ? "—" : String(value);
const statusOf = (item) => clearanceComplete(item) ? "Approved" : String(cv(item, "status", "Status", "overallStatus", "OverallStatus", "clearanceStatus", "ClearanceStatus") || "Pending");
const statusClass = (value) => { const status = String(value || "").toLowerCase(); return ["approved", "good", "cleared", "completed"].includes(status) ? "completed" : ["rejected", "failed"].includes(status) ? "error" : "pending"; };

export default function EmployeeClearanceSection({ resignationId, approved, clearance, loading, onRefresh }) {
  const readOnly = isEmployee();
  const [starting, setStarting] = useState(false), [saving, setSaving] = useState(""), [remarks, setRemarks] = useState({});
  const departments = useMemo(() => [["HR", "HR", cv(clearance, "hrStatus", "HrStatus"), cv(clearance, "hrRemarks", "HrRemarks")], ["IT", "IT", cv(clearance, "itStatus", "ItStatus"), cv(clearance, "itRemarks", "ItRemarks")], ["Finance", "Finance", cv(clearance, "financeStatus", "FinanceStatus"), cv(clearance, "financeRemarks", "FinanceRemarks")], ["Administration", "Admin", cv(clearance, "adminStatus", "AdminStatus"), cv(clearance, "adminRemarks", "AdminRemarks")]], [clearance]);
  const start = async () => { setStarting(true); try { await createClearance({ resignationId }); toastSuccess("Employee clearance started."); await onRefresh(); } catch (error) { if ([400, 404, 409].includes(error?.response?.status)) await onRefresh(); else toastError(clearanceError(error)); } finally { setStarting(false); } };
  const clearDepartment = async (label, department) => { const id = cv(clearance, "clearanceId", "ClearanceId", "clearanceID", "ClearanceID", "id", "Id"); if (!id) return toastError("Clearance ID is missing."); setSaving(label); try { await updateDepartmentClearance({ clearanceId: Number(id), department, isApproved: true, remarks: String(remarks[label] || "") }); toastSuccess(`${label} clearance updated.`); setRemarks((current) => ({ ...current, [label]: "" })); await onRefresh(); } catch (error) { toastError(clearanceError(error)); } finally { setSaving(""); } };
  if (!approved) return null;
  if (loading) return <section className="clearance-section"><h3>Employee Clearance</h3><div className="skeleton-line" /><div className="skeleton-line" /></section>;
  return <section className="clearance-section"><h3>Employee Clearance</h3>{!clearance ? <><p>Clearance has not been started for this approved resignation.</p>{!readOnly && <button type="button" onClick={start} disabled={starting}>{starting ? "Starting…" : "Start Clearance"}</button>}</> : <><p>Overall Clearance Status: <span className={`clearance-chip ${statusClass(statusOf(clearance))}`}>{displayValue(statusOf(clearance))}</span></p><div className="resignation-detail-grid"><div><small>Employee</small><strong>{displayValue(cv(clearance, "employeeName", "EmployeeName"))}</strong></div><div><small>Employee ID</small><strong>{displayValue(cv(clearance, "employeeId", "EmployeeId", "employee_Id"))}</strong></div><div><small>Resignation ID</small><strong>{resignationId}</strong></div><div><small>Last Working Date</small><strong>{displayValue(String(cv(clearance, "lastWorkingDate", "LastWorkingDate") || "").slice(0, 10))}</strong></div></div><div className="clearance-table-wrap"><table className="clearance-table"><thead><tr><th>Department</th><th>Status</th><th>Remarks</th><th>Action</th></tr></thead><tbody>{departments.map(([label, department, status, existingRemarks]) => <tr key={label}><td>{label}</td><td><span className={`clearance-chip ${statusClass(status)}`}>{displayValue(status)}</span></td><td>{readOnly ? displayValue(existingRemarks) : <input value={remarks[label] ?? ""} placeholder={displayValue(existingRemarks)} onChange={(event) => setRemarks((current) => ({ ...current, [label]: event.target.value }))} />}</td><td>{!readOnly && <button type="button" onClick={() => clearDepartment(label, department)} disabled={saving === label}>{saving === label ? "Saving…" : "Clear"}</button>}</td></tr>)}</tbody></table></div></>}</section>;
}
