import React, { useEffect, useState } from "react";
import { FaSearch } from "react-icons/fa";
import { useSearchParams } from "react-router-dom";
import EmptyState from "../components/EmptyState";
import { searchSuperAdmin } from "../services/superAdminService";
import "./SuperAdmin.css";

const getValue = (item, keys) => keys.map((key) => item?.[key]).find((value) => value !== undefined && value !== null && value !== "") || "-";
function ResultSection({ title, items, fields }) { return <section className="super-admin-search-section"><h2>{title} <span>{items.length}</span></h2>{items.length ? <div className="super-admin-search-results">{items.map((item, index) => <article key={item.id || item.organizationId || item.adminId || item.employeeId || index}>{fields.map(([label, keys]) => <p key={label}><span>{label}</span><strong>{getValue(item, keys)}</strong></p>)}</article>)}</div> : <EmptyState message={`No ${title.toLowerCase()} found.`} />}</section>; }
function SuperAdminSearch() { const [params] = useSearchParams(); const query = params.get("query") || ""; const [result, setResult] = useState(null); const [error, setError] = useState(""); useEffect(() => { if (!query.trim()) { setResult(null); return; } let active = true; setError(""); setResult(null); searchSuperAdmin(query).then((response) => { if (active) setResult(response); }).catch(() => { if (active) setError("Search could not be completed. Please try again."); }); return () => { active = false; }; }, [query]); return <main className="super-admin-page super-admin-search-page"><div className="page-header"><div><h1>Platform Search</h1><p>Results for {query ? <strong>“{query}”</strong> : "your search"}.</p></div></div>{error && <p className="super-admin-settings-error" role="alert">{error}</p>}{!query ? <EmptyState message="Enter a search term in the header to find organizations, admins, or employees." /> : !result ? <div className="super-admin-empty">Searching...</div> : <><p className="super-admin-search-total"><FaSearch /> {result.totalMatches ?? 0} match(es) found</p><ResultSection title="Organizations" items={result.organizations || []} fields={[["Name", ["organizationName", "name"]], ["Email", ["officialEmail", "email"]], ["Status", ["status"]]]} /><ResultSection title="Admins" items={result.admins || []} fields={[["Name", ["name", "fullName"]], ["Email", ["email"]], ["Status", ["status", "isActive"]]]} /><ResultSection title="Employees" items={result.employees || []} fields={[["Name", ["employeeName", "name", "fullName"]], ["Email", ["email"]], ["Employee ID", ["employeeId", "id"]]]} /></>}</main>; }
export default SuperAdminSearch;
