export const superAdminModules = [
  "Dashboard",
  "Employees",
  "Attendance",
  "Leave Management",
  "Payroll",
  "Projects",
  "Assets",
  "Documents",
  "Recruitment",
  "Task Management",
  "Reports",
  "Support",
  "Notifications",
  "Settings",
];

export const clients = [
  {
    id: "CL-001",
    logo: "PT",
    companyName: "Honeywell IT Solutions",
    code: "HONEYWELL",
    contactPerson: "Ravi Kumar",
    officialEmail: "admin@honeywellitsolutions.com",
    phone: "9876543210",
    plan: "Enterprise",
    employeeLimit: 500,
    currentEmployees: 342,
    renewalDate: "2026-12-31",
    status: "Active",
    industry: "Technology",
    gst: "36AAICP1234A1Z5",
    pan: "AAICP1234A",
    website: "https://honeywellitsolutions.com",
    address: "Hyderabad, Telangana, India",
    adminName: "Ravi Kumar",
    adminEmail: "admin@honeywellitsolutions.com",
    storageLimit: "500 GB",
    storageUsed: "212 GB",
    modules: superAdminModules.filter((module) => module !== "Settings"),
    billingSummary: "₹2,40,000 paid yearly",
    recentActivity: ["Subscription renewed", "Client admin created", "Support ticket resolved"],
  },
  {
    id: "CL-002",
    logo: "AB",
    companyName: "ABC Technologies",
    code: "ABC",
    contactPerson: "Sneha Reddy",
    officialEmail: "hr@abctech.com",
    phone: "9123456780",
    plan: "Professional",
    employeeLimit: 250,
    currentEmployees: 168,
    renewalDate: "2026-10-15",
    status: "Active",
    industry: "IT Services",
    gst: "29ABCDE1234F1Z1",
    pan: "ABCDE1234F",
    website: "https://abctech.com",
    address: "Bengaluru, Karnataka, India",
    adminName: "Sneha Reddy",
    adminEmail: "hr@abctech.com",
    storageLimit: "250 GB",
    storageUsed: "94 GB",
    modules: superAdminModules.slice(0, 11),
    billingSummary: "₹78,000 paid quarterly",
    recentActivity: ["Employee limit updated", "Invoice generated", "Demo converted"],
  },
  {
    id: "CL-003",
    logo: "XY",
    companyName: "XYZ Pvt Ltd",
    code: "XYZ",
    contactPerson: "Amit Shah",
    officialEmail: "admin@xyzpvt.com",
    phone: "9988776655",
    plan: "Starter",
    employeeLimit: 75,
    currentEmployees: 48,
    renewalDate: "2026-08-20",
    status: "Inactive",
    industry: "Manufacturing",
    gst: "27XYZAB9876C1Z2",
    pan: "XYZAB9876C",
    website: "https://xyzpvt.com",
    address: "Pune, Maharashtra, India",
    adminName: "Amit Shah",
    adminEmail: "admin@xyzpvt.com",
    storageLimit: "50 GB",
    storageUsed: "17 GB",
    modules: ["Dashboard", "Employees", "Attendance", "Leave Management", "Reports"],
    billingSummary: "₹18,000 overdue",
    recentActivity: ["Payment reminder sent", "Support ticket opened", "Trial ended"],
  },
];

export const payments = [
  { invoice: "INV-2026-071", company: "Honeywell IT Solutions", subscription: "Enterprise", month: "July 2026", amount: "₹2,40,000", dueDate: "2026-07-10", status: "Paid" },
  { invoice: "INV-2026-072", company: "ABC Technologies", subscription: "Professional", month: "July 2026", amount: "₹78,000", dueDate: "2026-07-18", status: "Pending" },
  { invoice: "INV-2026-073", company: "XYZ Pvt Ltd", subscription: "Starter", month: "July 2026", amount: "₹18,000", dueDate: "2026-07-05", status: "Overdue" },
];

export const supportTickets = [
  { id: "SUP-1001", company: "ABC Technologies", subject: "Payroll report mismatch", priority: "High", status: "Open", assignedTo: "Support Lead", created: "2026-07-28" },
  { id: "SUP-1002", company: "Honeywell IT Solutions", subject: "Attendance sync question", priority: "Medium", status: "Assigned", assignedTo: "Meera", created: "2026-07-27" },
  { id: "SUP-1003", company: "XYZ Pvt Ltd", subject: "Subscription renewal help", priority: "Critical", status: "Open", assignedTo: "Rohan", created: "2026-07-26" },
];

export const demoRequests = [
  { company: "Nexa Labs", contact: "Kiran Rao", email: "kiran@nexalabs.com", phone: "9000011111", employees: "101-250", preferredDate: "2026-08-02", status: "New", notes: "Interested in payroll and attendance." },
  { company: "Metro Retail", contact: "Pooja Nair", email: "pooja@metroretail.com", phone: "9000022222", employees: "251-500", preferredDate: "2026-08-05", status: "Scheduled", notes: "Needs multi-branch demo." },
  { company: "Qube Finance", contact: "Vikram Sen", email: "vikram@qubefin.com", phone: "9000033333", employees: "51-100", preferredDate: "2026-08-08", status: "Converted", notes: "Converted to Professional plan." },
];

export const plans = [
  { name: "Starter", price: "₹18,000", billingCycle: "Monthly", employees: 75, admins: 2, storage: "50 GB", modules: "Core HR, Attendance, Leave", support: "Email", status: "Active" },
  { name: "Professional", price: "₹78,000", billingCycle: "Quarterly", employees: 250, admins: 6, storage: "250 GB", modules: "HR, Payroll, Projects, Reports", support: "Priority", status: "Active" },
  { name: "Enterprise", price: "₹2,40,000", billingCycle: "Yearly", employees: 500, admins: 15, storage: "500 GB", modules: "All modules", support: "Dedicated", status: "Active" },
  { name: "Custom", price: "Custom", billingCycle: "Yearly", employees: "Custom", admins: "Custom", storage: "Custom", modules: "Configured per client", support: "Dedicated", status: "Draft" },
];
